package com.jlmd.android.circularloadinganimation.view.animator;

/**
 * @author jlmd
 */
public enum AnimationState {

  MAIN_CIRCLE_TRANSLATED_TOP, MAIN_CIRCLE_SCALED_UP, MAIN_CIRCLE_TRANSLATED_BOTTOM_FROM_MIDDLE,
  MAIN_CIRCLE_SCALED_DISAPPEAR, MAIN_CIRCLE_FILLED_TOP, SECONDARY_CIRCLE_FINISHED,
  SIDE_ARCS_RESIZED_TOP, MAIN_CIRCLE_DRAWN_TOP
}
